    # render.yaml
    # This file defines services for Render.
    # It should be placed in the root of your Git repository.

    services:
      # Frontend Service (Static Site)
      - type: static
        name: cogniwrite-pro-frontend
        buildCommand: npm run build
        staticPublishPath: frontend-cogniwrite/dist # Assuming Vite build output
        # Environment variables for frontend will be added on Netlify later
        # envVars:
        #   - key: VITE_API_BASE_URL
        #     value: https://your-backend-app-name.onrender.com/api # Placeholder for backend URL

      # Backend Service (Web Service)
      - type: web
        name: cogniwrite-pro-backend
        env: java # Explicitly tell Render this is a Java service
        rootDir: backend-cogniwrite # Specify the root directory for this service
        buildCommand: ./mvnw clean install -DskipTests
        startCommand: java -jar target/cogniwrite-0.0.1-SNAPSHOT.jar # Ensure JAR name matches
        plan: free # Use the free plan
        # Add your environment variables here directly, or reference them from Render's dashboard
        envVars:
          # Database Connection (from your PostgreSQL service)
          - key: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://cogniwriteuser:CgpHDHMrgMZF7AB3P71Y5CIPrEC1iOM7@dpg-d20ein95pdvs73cfblp0-a.singapore-postgres.render.com/cogniwritepro
          - key: SPRING_DATASOURCE_USERNAME
            value: cogniwriteuser
          - key: SPRING_DATASOURCE_PASSWORD
            value: CgpHDHMrgMZF7AB3P71Y5CIPrEC1iOM7
          - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: org.postgresql.Driver
          - key: SPRING_JPA_DATABASE_PLATFORM
            value: org.hibernate.dialect.PostgreSQLDialect
          - key: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update # Set to 'update' for initial table creation

          # LLM API Keys
          - key: MISTRAL_API_KEY
            value: YOUR_ACTUAL_MISTRAL_API_KEY # REPLACE WITH YOUR KEY
          - key: MISTRAL_API_URL
            value: https://api.mistral.ai/v1
          - key: MISTRAL_MODEL
            value: /chat/completions
          - key: GEMINI_API_KEY
            value: YOUR_ACTUAL_GEMINI_API_KEY # REPLACE WITH YOUR KEY

          # JWT Secret
          - key: JWT_SECRET
            value: A_VERY_LONG_RANDOM_STRING_FOR_JWT_SECURITY # REPLACE WITH A STRONG, RANDOM KEY
          - key: JWT_EXPIRATION_MS
            value: "86400000" # Value must be a string in YAML
    